import type { ExamHistory, MockExam, Problem, SampleCase } from "./types";

const starter = (lines: string[]) => `${lines.join("\n")}\n`;

const problem = (
  id: number,
  title: string,
  level: Problem["level"],
  points: number,
  description: string[],
  inputDescription: string,
  outputDescription: string,
  constraints: string[],
  samples: SampleCase[],
  starterCode: string,
  timeLimitMs = 2000,
  memoryLimitMb = 128,
): Problem => ({
  id,
  title,
  level,
  points,
  timeLimitMs,
  memoryLimitMb,
  description,
  inputDescription,
  outputDescription,
  constraints,
  samples,
  starterCode,
});

export const mockExams: MockExam[] = [
  {
    roomCode: "HUF-2026",
    title: "클라우드 컴퓨팅 실습 평가",
    course: "Cloud Computing",
    professor: "김하늘",
    examType: "중간고사",
    durationSeconds: 60 * 75,
    startsAt: "2026-06-03T09:00:00+09:00",
    problems: [
      problem(
        1,
        "A+B 자동 채점",
        "Easy",
        15,
        [
          "두 정수 A와 B를 입력받아 합을 출력하세요.",
          "표준 입력으로 주어진 값을 읽고, 정답은 표준 출력으로만 출력해야 합니다.",
        ],
        "첫째 줄에 정수 A와 B가 공백으로 구분되어 주어집니다.",
        "A+B의 값을 한 줄에 출력합니다.",
        ["-1,000 <= A, B <= 1,000", "불필요한 문장은 출력하지 않습니다."],
        [
          { input: "1 2", output: "3" },
          { input: "-4 9", output: "5" },
        ],
        starter(["a, b = map(int, input().split())", "# TODO: 두 수의 합을 출력하세요."]),
      ),
      problem(
        2,
        "최댓값 찾기",
        "Easy",
        15,
        [
          "정수 배열이 주어졌을 때 가장 큰 값을 출력하세요.",
          "배열의 길이는 첫 줄에 주어지고, 둘째 줄에 배열 원소가 주어집니다.",
        ],
        "첫째 줄에 N, 둘째 줄에 N개의 정수가 주어집니다.",
        "배열에서 가장 큰 정수를 출력합니다.",
        ["1 <= N <= 100,000", "-10^9 <= 각 원소 <= 10^9"],
        [{ input: "5\n3 1 9 2 7", output: "9" }],
        starter([
          "n = int(input())",
          "arr = list(map(int, input().split()))",
          "# TODO: 최댓값을 출력하세요.",
        ]),
      ),
      problem(
        3,
        "요청 로그 집계",
        "Medium",
        20,
        [
          "API 서버 로그에서 성공 응답의 개수를 집계하세요.",
          "각 로그는 HTTP status code 하나로 표현되며, 200 이상 300 미만이면 성공입니다.",
        ],
        "첫째 줄에 로그 수 N, 다음 N줄에 status code가 주어집니다.",
        "성공 응답의 개수를 출력합니다.",
        ["1 <= N <= 200,000", "100 <= status code <= 599"],
        [{ input: "6\n200\n201\n404\n500\n204\n302", output: "3" }],
        starter([
          "n = int(input())",
          "count = 0",
          "for _ in range(n):",
          "    status = int(input())",
          "    # TODO: 성공 응답을 세어보세요.",
          "print(count)",
        ]),
        3000,
        256,
      ),
      problem(
        4,
        "큐 처리 시간",
        "Medium",
        15,
        [
          "하나의 작업자가 순서대로 요청을 처리할 때 각 요청의 완료 시각을 계산하세요.",
          "각 요청은 도착 시각과 처리 시간이 주어지며, 작업자는 한 번에 하나만 처리합니다.",
        ],
        "첫째 줄에 N, 다음 N줄에 도착 시각 A와 처리 시간 T가 주어집니다.",
        "각 요청의 완료 시각을 한 줄씩 출력합니다.",
        ["1 <= N <= 100,000", "0 <= A <= 10^9", "1 <= T <= 10^6"],
        [{ input: "3\n0 3\n1 2\n7 1", output: "3\n5\n8" }],
        starter([
          "n = int(input())",
          "current = 0",
          "for _ in range(n):",
          "    arrived_at, duration = map(int, input().split())",
          "    # TODO: 완료 시각을 계산하세요.",
        ]),
      ),
      problem(
        5,
        "캐시 만료 계산",
        "Medium",
        15,
        [
          "캐시에 저장된 항목의 생성 시각과 TTL이 주어질 때 조회 시각에 유효한 항목 수를 구하세요.",
          "항목은 생성 시각 이상, 생성 시각+TTL 미만에서만 유효합니다.",
        ],
        "첫째 줄에 N과 Q, 다음 N줄에 생성 시각과 TTL, 다음 Q줄에 조회 시각이 주어집니다.",
        "각 조회마다 유효한 캐시 항목 수를 출력합니다.",
        ["1 <= N, Q <= 2,000", "0 <= 시각 <= 10^9"],
        [{ input: "3 2\n0 5\n2 4\n7 3\n3\n7", output: "2\n1" }],
        starter([
          "n, q = map(int, input().split())",
          "items = [tuple(map(int, input().split())) for _ in range(n)]",
          "for _ in range(q):",
          "    target = int(input())",
          "    # TODO: 유효한 항목 수를 출력하세요.",
        ]),
        3000,
        256,
      ),
      problem(
        6,
        "서버 증설 계획",
        "Hard",
        20,
        [
          "시간대별 요청량과 서버 한 대의 처리량이 주어졌을 때 필요한 최소 서버 수를 계산하세요.",
          "각 시간대는 독립적으로 계산하며 가장 많이 필요한 서버 수를 출력합니다.",
        ],
        "첫째 줄에 N과 C, 둘째 줄에 N개의 요청량이 주어집니다.",
        "필요한 최소 서버 수의 최댓값을 출력합니다.",
        ["1 <= N <= 100,000", "1 <= C <= 10^9", "0 <= 요청량 <= 10^12"],
        [{ input: "5 100\n40 120 0 270 99", output: "3" }],
        starter([
          "n, capacity = map(int, input().split())",
          "requests = list(map(int, input().split()))",
          "# TODO: 필요한 서버 수의 최댓값을 출력하세요.",
        ]),
      ),
    ],
  },
  {
    roomCode: "ALG-MID",
    title: "알고리즘 문제 해결 중간평가",
    course: "Algorithm",
    professor: "이서준",
    examType: "중간고사",
    durationSeconds: 60 * 90,
    startsAt: "2026-06-05T13:30:00+09:00",
    problems: [
      problem(
        1,
        "두 수의 합 쌍",
        "Easy",
        15,
        [
          "서로 다른 정수 N개와 목표값 X가 주어질 때 합이 X가 되는 쌍의 개수를 구하세요.",
          "한 원소는 한 쌍에서 한 번만 사용할 수 있습니다.",
        ],
        "첫째 줄에 N과 X, 둘째 줄에 N개의 정수가 주어집니다.",
        "합이 X가 되는 서로 다른 쌍의 개수를 출력합니다.",
        ["2 <= N <= 100,000", "-10^9 <= 원소, X <= 10^9"],
        [{ input: "6 10\n1 9 5 5 3 7", output: "3" }],
        starter([
          "n, target = map(int, input().split())",
          "numbers = list(map(int, input().split()))",
          "# TODO: 두 수의 합 쌍을 세어보세요.",
        ]),
      ),
      problem(
        2,
        "올바른 괄호",
        "Easy",
        15,
        [
          "괄호 문자열이 올바른지 판별하세요.",
          "열린 괄호는 반드시 나중에 등장하는 닫힌 괄호와 짝을 이루어야 합니다.",
        ],
        "한 줄에 괄호 문자열 S가 주어집니다.",
        "올바른 괄호 문자열이면 YES, 아니면 NO를 출력합니다.",
        ["1 <= |S| <= 200,000", "S는 '('와 ')'로만 구성됩니다."],
        [
          { input: "(()())", output: "YES" },
          { input: "())(", output: "NO" },
        ],
        starter(["s = input().strip()", "# TODO: 올바른 괄호인지 출력하세요."]),
      ),
      problem(
        3,
        "문자열 압축 길이",
        "Medium",
        15,
        [
          "같은 문자가 연속해서 등장하는 구간을 문자와 개수로 압축합니다.",
          "압축된 문자열의 실제 내용이 아니라 길이만 출력하세요.",
        ],
        "한 줄에 문자열 S가 주어집니다.",
        "런렝스 압축 결과의 길이를 출력합니다.",
        ["1 <= |S| <= 200,000", "S는 알파벳 소문자로만 구성됩니다."],
        [{ input: "aaabbc", output: "6" }],
        starter(["s = input().strip()", "# TODO: 압축 결과 길이를 계산하세요."]),
      ),
      problem(
        4,
        "회의실 배정",
        "Medium",
        20,
        [
          "시작 시각과 종료 시각이 주어진 회의 중 겹치지 않게 선택할 수 있는 최대 개수를 구하세요.",
          "한 회의가 끝나는 시각에 다른 회의를 바로 시작할 수 있습니다.",
        ],
        "첫째 줄에 N, 다음 N줄에 시작 시각과 종료 시각이 주어집니다.",
        "선택 가능한 회의의 최대 개수를 출력합니다.",
        ["1 <= N <= 100,000", "0 <= 시작 < 종료 <= 10^9"],
        [{ input: "4\n1 3\n2 4\n3 5\n0 7", output: "2" }],
        starter([
          "n = int(input())",
          "meetings = [tuple(map(int, input().split())) for _ in range(n)]",
          "# TODO: 최대 회의 수를 출력하세요.",
        ]),
        3000,
        256,
      ),
      problem(
        5,
        "미로 최단 거리",
        "Hard",
        20,
        [
          "0은 이동 가능한 칸, 1은 벽인 격자에서 왼쪽 위에서 오른쪽 아래까지의 최단 거리를 구하세요.",
          "상하좌우로만 이동할 수 있으며 시작 칸도 거리 1로 셉니다.",
        ],
        "첫째 줄에 N과 M, 다음 N줄에 0과 1로 이루어진 격자가 주어집니다.",
        "도착할 수 있으면 최단 거리, 없으면 -1을 출력합니다.",
        ["2 <= N, M <= 1,000", "격자 값은 0 또는 1입니다."],
        [{ input: "3 4\n0000\n1110\n0000", output: "6" }],
        starter([
          "from collections import deque",
          "n, m = map(int, input().split())",
          "grid = [input().strip() for _ in range(n)]",
          "# TODO: BFS로 최단 거리를 구하세요.",
        ]),
        4000,
        512,
      ),
      problem(
        6,
        "구간 합 질의",
        "Medium",
        15,
        [
          "정수 배열과 여러 구간 질의가 주어질 때 각 구간의 합을 빠르게 구하세요.",
          "구간은 1-based 인덱스의 양끝 포함 범위입니다.",
        ],
        "첫째 줄에 N과 Q, 둘째 줄에 배열, 다음 Q줄에 L과 R이 주어집니다.",
        "각 질의의 구간 합을 한 줄씩 출력합니다.",
        ["1 <= N, Q <= 200,000", "-10^9 <= 원소 <= 10^9"],
        [{ input: "5 3\n1 2 3 4 5\n1 3\n2 5\n4 4", output: "6\n14\n4" }],
        starter([
          "n, q = map(int, input().split())",
          "arr = list(map(int, input().split()))",
          "# TODO: 누적합을 만든 뒤 질의를 처리하세요.",
        ]),
        3000,
        256,
      ),
    ],
  },
  {
    roomCode: "DS-FIN",
    title: "자료구조 기말 실습",
    course: "Data Structures",
    professor: "박민재",
    examType: "기말고사",
    durationSeconds: 60 * 100,
    startsAt: "2026-06-10T10:00:00+09:00",
    problems: [
      problem(
        1,
        "스택 명령 처리",
        "Easy",
        10,
        [
          "push, pop, size, empty, top 명령을 처리하는 스택을 구현하세요.",
          "pop과 top은 스택이 비어 있으면 -1을 출력합니다.",
        ],
        "첫째 줄에 명령 수 N, 다음 N줄에 명령이 주어집니다.",
        "출력이 필요한 명령의 결과를 한 줄씩 출력합니다.",
        ["1 <= N <= 100,000", "push 값은 정수입니다."],
        [{ input: "5\npush 3\ntop\npop\nempty\npop", output: "3\n3\n1\n-1" }],
        starter([
          "import sys",
          "n = int(sys.stdin.readline())",
          "stack = []",
          "# TODO: 스택 명령을 처리하세요.",
        ]),
      ),
      problem(
        2,
        "회전 큐 시뮬레이션",
        "Medium",
        15,
        [
          "1부터 N까지 들어 있는 덱에서 목표 숫자들을 순서대로 제거하려고 합니다.",
          "왼쪽 또는 오른쪽 회전을 사용할 때 필요한 최소 회전 수를 구하세요.",
        ],
        "첫째 줄에 N과 M, 둘째 줄에 제거할 M개의 숫자가 주어집니다.",
        "최소 회전 횟수를 출력합니다.",
        ["1 <= M <= N <= 10,000"],
        [{ input: "10 3\n2 9 5", output: "8" }],
        starter([
          "from collections import deque",
          "n, m = map(int, input().split())",
          "targets = list(map(int, input().split()))",
          "# TODO: 최소 회전 횟수를 계산하세요.",
        ]),
      ),
      problem(
        3,
        "절댓값 힙",
        "Medium",
        15,
        [
          "정수를 삽입하고, 절댓값이 가장 작은 수를 제거하는 자료구조를 구현하세요.",
          "절댓값이 같다면 실제 값이 작은 수를 먼저 제거합니다.",
        ],
        "첫째 줄에 연산 수 N, 다음 N줄에 정수 X가 주어집니다. X가 0이면 제거 연산입니다.",
        "제거 연산마다 제거한 값을 출력하고, 비어 있으면 0을 출력합니다.",
        ["1 <= N <= 100,000", "-2^31 < X < 2^31"],
        [{ input: "6\n1\n-1\n0\n0\n0\n2", output: "-1\n1\n0" }],
        starter([
          "import heapq",
          "n = int(input())",
          "heap = []",
          "# TODO: 절댓값 힙 연산을 처리하세요.",
        ]),
      ),
      problem(
        4,
        "네트워크 연결 요소",
        "Medium",
        15,
        [
          "무방향 그래프의 연결 요소 개수를 구하세요.",
          "정점 번호는 1부터 N까지입니다.",
        ],
        "첫째 줄에 N과 M, 다음 M줄에 간선 U V가 주어집니다.",
        "연결 요소의 개수를 출력합니다.",
        ["1 <= N <= 100,000", "0 <= M <= 200,000"],
        [{ input: "5 3\n1 2\n2 3\n4 5", output: "2" }],
        starter([
          "n, m = map(int, input().split())",
          "graph = [[] for _ in range(n + 1)]",
          "# TODO: 그래프를 만들고 연결 요소를 세세요.",
        ]),
        3000,
        256,
      ),
      problem(
        5,
        "트리 부모 찾기",
        "Medium",
        15,
        [
          "루트가 1인 트리에서 각 노드의 부모를 구하세요.",
          "2번 노드부터 N번 노드까지 부모를 순서대로 출력합니다.",
        ],
        "첫째 줄에 N, 다음 N-1줄에 트리의 간선이 주어집니다.",
        "각 노드의 부모 번호를 한 줄씩 출력합니다.",
        ["2 <= N <= 100,000"],
        [{ input: "5\n1 2\n1 3\n2 4\n3 5", output: "1\n1\n2\n3" }],
        starter([
          "from collections import deque",
          "n = int(input())",
          "graph = [[] for _ in range(n + 1)]",
          "# TODO: BFS 또는 DFS로 부모를 찾으세요.",
        ]),
        3000,
        256,
      ),
      problem(
        6,
        "출석 해시 조회",
        "Easy",
        10,
        [
          "수강생 명단과 출석 기록이 주어질 때 결석한 학생 이름을 사전순으로 출력하세요.",
          "동명이인은 없다고 가정합니다.",
        ],
        "첫째 줄에 N과 M, 다음 N줄에 명단, 다음 M줄에 출석한 이름이 주어집니다.",
        "결석한 학생 이름을 사전순으로 한 줄씩 출력합니다.",
        ["1 <= M <= N <= 100,000", "이름은 알파벳 소문자입니다."],
        [{ input: "4 2\namy\nben\ncody\ndana\nben\namy", output: "cody\ndana" }],
        starter([
          "n, m = map(int, input().split())",
          "students = {input().strip() for _ in range(n)}",
          "# TODO: 출석한 학생을 제외하고 출력하세요.",
        ]),
      ),
      problem(
        7,
        "LRU 캐시 상태",
        "Hard",
        20,
        [
          "캐시 용량과 페이지 접근 순서가 주어질 때 LRU 정책으로 처리한 뒤 캐시 상태를 출력하세요.",
          "가장 최근에 사용된 페이지부터 순서대로 출력합니다.",
        ],
        "첫째 줄에 캐시 용량 C와 접근 수 N, 둘째 줄에 N개의 페이지 번호가 주어집니다.",
        "최종 캐시 상태를 최근 사용 순서대로 출력합니다.",
        ["1 <= C <= 100,000", "1 <= N <= 200,000"],
        [{ input: "3 7\n1 2 3 2 4 1 5", output: "5 1 4" }],
        starter([
          "capacity, n = map(int, input().split())",
          "pages = list(map(int, input().split()))",
          "# TODO: LRU 캐시를 시뮬레이션하세요.",
        ]),
        4000,
        512,
      ),
    ],
  },
  {
    roomCode: "PY-MID",
    title: "Python 프로그래밍 중간고사",
    course: "Python Programming",
    professor: "정유진",
    examType: "중간고사",
    durationSeconds: 60 * 60,
    startsAt: "2026-06-12T15:00:00+09:00",
    problems: [
      problem(
        1,
        "단어 뒤집기",
        "Easy",
        15,
        [
          "여러 단어가 주어질 때 각 단어를 뒤집어 출력하세요.",
          "단어의 순서는 유지해야 합니다.",
        ],
        "첫째 줄에 단어 수 N, 다음 N줄에 단어가 주어집니다.",
        "각 단어를 뒤집어 한 줄씩 출력합니다.",
        ["1 <= N <= 10,000", "단어 길이는 1 이상 100 이하입니다."],
        [{ input: "3\nhufs\nsolve\npython", output: "sfuh\nevlos\nnohtyp" }],
        starter(["n = int(input())", "for _ in range(n):", "    word = input().strip()"]),
      ),
      problem(
        2,
        "소수 개수 세기",
        "Easy",
        15,
        [
          "주어진 정수들 중 소수의 개수를 구하세요.",
          "1은 소수가 아닙니다.",
        ],
        "첫째 줄에 N, 둘째 줄에 N개의 정수가 주어집니다.",
        "소수의 개수를 출력합니다.",
        ["1 <= N <= 1,000", "1 <= 정수 <= 10,000"],
        [{ input: "4\n1 3 5 8", output: "2" }],
        starter([
          "n = int(input())",
          "numbers = list(map(int, input().split()))",
          "# TODO: 소수를 판별해 개수를 출력하세요.",
        ]),
      ),
      problem(
        3,
        "계단 오르기",
        "Medium",
        20,
        [
          "한 번에 1칸 또는 2칸을 오를 수 있을 때 N번째 계단에 도달하는 방법의 수를 구하세요.",
          "정답이 커질 수 있으므로 1,000,000,007로 나눈 나머지를 출력합니다.",
        ],
        "첫째 줄에 계단 수 N이 주어집니다.",
        "도달 방법 수를 출력합니다.",
        ["1 <= N <= 1,000,000"],
        [{ input: "5", output: "8" }],
        starter(["n = int(input())", "MOD = 1_000_000_007", "# TODO: DP로 방법 수를 구하세요."]),
        3000,
        256,
      ),
      problem(
        4,
        "좌표 정렬",
        "Medium",
        15,
        [
          "2차원 좌표가 주어질 때 x좌표 오름차순, x가 같으면 y좌표 오름차순으로 정렬하세요.",
          "정렬된 좌표를 한 줄씩 출력합니다.",
        ],
        "첫째 줄에 N, 다음 N줄에 x y가 주어집니다.",
        "정렬된 좌표를 출력합니다.",
        ["1 <= N <= 100,000", "-100,000 <= x, y <= 100,000"],
        [{ input: "4\n3 4\n1 2\n1 -1\n2 2", output: "1 -1\n1 2\n2 2\n3 4" }],
        starter([
          "n = int(input())",
          "points = [tuple(map(int, input().split())) for _ in range(n)]",
          "# TODO: 좌표를 정렬해 출력하세요.",
        ]),
      ),
      problem(
        5,
        "평균 넘는 학생",
        "Easy",
        15,
        [
          "각 반의 점수 목록이 주어질 때 평균을 넘는 학생의 비율을 구하세요.",
          "비율은 소수점 셋째 자리까지 출력합니다.",
        ],
        "첫째 줄에 테스트 수 T, 각 테스트는 학생 수와 점수들이 한 줄에 주어집니다.",
        "각 반마다 평균을 넘는 학생 비율을 출력합니다.",
        ["1 <= T <= 100", "1 <= 학생 수 <= 1,000"],
        [{ input: "1\n5 50 50 70 80 100", output: "40.000%" }],
        starter([
          "t = int(input())",
          "for _ in range(t):",
          "    data = list(map(int, input().split()))",
          "    # TODO: 평균 초과 비율을 출력하세요.",
        ]),
      ),
      problem(
        6,
        "행렬 덧셈",
        "Easy",
        20,
        [
          "크기가 같은 두 행렬 A와 B가 주어질 때 A+B를 출력하세요.",
          "각 행의 원소는 공백으로 구분합니다.",
        ],
        "첫째 줄에 N과 M, 다음 N줄에 A, 다음 N줄에 B가 주어집니다.",
        "두 행렬의 합을 N줄에 걸쳐 출력합니다.",
        ["1 <= N, M <= 100", "-1,000 <= 원소 <= 1,000"],
        [{ input: "2 3\n1 2 3\n4 5 6\n6 5 4\n3 2 1", output: "7 7 7\n7 7 7" }],
        starter([
          "n, m = map(int, input().split())",
          "a = [list(map(int, input().split())) for _ in range(n)]",
          "b = [list(map(int, input().split())) for _ in range(n)]",
          "# TODO: 행렬 합을 출력하세요.",
        ]),
      ),
    ],
  },
  {
    roomCode: "SE-FIN",
    title: "소프트웨어 공학 기말 코딩",
    course: "Software Engineering",
    professor: "최도윤",
    examType: "기말고사",
    durationSeconds: 60 * 120,
    startsAt: "2026-06-17T09:30:00+09:00",
    problems: [
      problem(
        1,
        "예산 상한 탐색",
        "Medium",
        10,
        [
          "부서별 요청 예산과 총 예산이 주어질 때 가능한 최대 상한액을 구하세요.",
          "요청 예산이 상한액보다 크면 상한액만 배정합니다.",
        ],
        "첫째 줄에 N, 둘째 줄에 요청 예산, 셋째 줄에 총 예산 M이 주어집니다.",
        "가능한 최대 상한액을 출력합니다.",
        ["1 <= N <= 100,000", "1 <= 예산 <= 10^9"],
        [{ input: "4\n120 110 140 150\n485", output: "127" }],
        starter([
          "n = int(input())",
          "requests = list(map(int, input().split()))",
          "budget = int(input())",
          "# TODO: 이분 탐색으로 상한액을 구하세요.",
        ]),
      ),
      problem(
        2,
        "문자 빈도 정렬",
        "Easy",
        10,
        [
          "문자열에 등장한 문자를 빈도 내림차순, 문자가 같으면 알파벳 오름차순으로 출력하세요.",
          "각 문자는 문자와 빈도를 공백으로 구분해 출력합니다.",
        ],
        "한 줄에 문자열 S가 주어집니다.",
        "정렬된 문자와 빈도를 한 줄씩 출력합니다.",
        ["1 <= |S| <= 100,000", "S는 알파벳 소문자로 구성됩니다."],
        [{ input: "banana", output: "a 3\nn 2\nb 1" }],
        starter(["from collections import Counter", "s = input().strip()", "# TODO: 빈도를 정렬해 출력하세요."]),
      ),
      problem(
        3,
        "평범한 배낭",
        "Medium",
        15,
        [
          "무게와 가치가 있는 물건을 골라 최대 가치를 얻으세요.",
          "각 물건은 한 번만 선택할 수 있습니다.",
        ],
        "첫째 줄에 N과 K, 다음 N줄에 물건의 무게 W와 가치 V가 주어집니다.",
        "담을 수 있는 최대 가치를 출력합니다.",
        ["1 <= N <= 100", "1 <= K <= 100,000"],
        [{ input: "4 7\n6 13\n4 8\n3 6\n5 12", output: "14" }],
        starter([
          "n, capacity = map(int, input().split())",
          "items = [tuple(map(int, input().split())) for _ in range(n)]",
          "# TODO: 0/1 배낭 DP를 구현하세요.",
        ]),
        3000,
        256,
      ),
      problem(
        4,
        "네트워크 지연 시간",
        "Hard",
        15,
        [
          "방향 그래프에서 시작 노드 K가 모든 노드에 신호를 보내는 데 걸리는 시간을 구하세요.",
          "도달할 수 없는 노드가 있으면 -1을 출력합니다.",
        ],
        "첫째 줄에 N, M, K, 다음 M줄에 U V W가 주어집니다.",
        "모든 노드가 신호를 받는 최소 시간을 출력합니다.",
        ["1 <= N <= 100,000", "1 <= M <= 200,000", "1 <= W <= 10^9"],
        [{ input: "4 3 1\n1 2 2\n1 3 5\n2 4 1", output: "3" }],
        starter([
          "import heapq",
          "n, m, start = map(int, input().split())",
          "graph = [[] for _ in range(n + 1)]",
          "# TODO: 다익스트라로 지연 시간을 구하세요.",
        ]),
        4000,
        512,
      ),
      problem(
        5,
        "작업 순서 정하기",
        "Medium",
        10,
        [
          "작업 간 선후 관계가 주어질 때 가능한 작업 순서를 하나 출력하세요.",
          "여러 답이 가능하면 번호가 작은 작업을 먼저 선택합니다.",
        ],
        "첫째 줄에 N과 M, 다음 M줄에 A B가 주어집니다. A는 B보다 먼저 해야 합니다.",
        "가능한 작업 순서를 공백으로 출력합니다.",
        ["1 <= N <= 100,000", "0 <= M <= 200,000"],
        [{ input: "4 3\n1 2\n1 3\n3 4", output: "1 2 3 4" }],
        starter([
          "import heapq",
          "n, m = map(int, input().split())",
          "# TODO: 위상 정렬을 구현하세요.",
        ]),
        3000,
        256,
      ),
      problem(
        6,
        "파일명 정렬",
        "Medium",
        10,
        [
          "파일명을 head, number, tail로 나누어 정렬하세요.",
          "head는 대소문자를 구분하지 않고, number는 숫자 값으로 비교합니다.",
        ],
        "첫째 줄에 파일 수 N, 다음 N줄에 파일명이 주어집니다.",
        "정렬된 파일명을 한 줄씩 출력합니다.",
        ["1 <= N <= 10,000", "number는 최대 5자리입니다."],
        [{ input: "3\nimg12.png\nimg10.png\nimg2.png", output: "img2.png\nimg10.png\nimg12.png" }],
        starter(["n = int(input())", "files = [input().strip() for _ in range(n)]", "# TODO: 파일명을 규칙대로 정렬하세요."]),
      ),
      problem(
        7,
        "최소 스패닝 트리 비용",
        "Hard",
        20,
        [
          "가중치가 있는 무방향 그래프에서 모든 정점을 연결하는 최소 비용을 구하세요.",
          "그래프는 항상 연결되어 있습니다.",
        ],
        "첫째 줄에 V와 E, 다음 E줄에 A B C가 주어집니다.",
        "최소 스패닝 트리의 총 비용을 출력합니다.",
        ["2 <= V <= 100,000", "1 <= E <= 200,000"],
        [{ input: "3 3\n1 2 1\n2 3 2\n1 3 5", output: "3" }],
        starter([
          "v, e = map(int, input().split())",
          "edges = [tuple(map(int, input().split())) for _ in range(e)]",
          "# TODO: 크루스칼 또는 프림으로 MST 비용을 구하세요.",
        ]),
        4000,
        512,
      ),
      problem(
        8,
        "개인정보 로그 마스킹",
        "Easy",
        10,
        [
          "로그 문자열에서 이메일 주소의 사용자명 일부를 마스킹하세요.",
          "사용자명은 첫 글자와 마지막 글자만 남기고 나머지는 '*'로 바꿉니다.",
        ],
        "첫째 줄에 로그 수 N, 다음 N줄에 이메일이 하나 포함된 로그가 주어집니다.",
        "마스킹된 로그를 한 줄씩 출력합니다.",
        ["1 <= N <= 10,000", "이메일 사용자명 길이는 2 이상입니다."],
        [{ input: "1\nlogin user alice@example.com success", output: "login user a***e@example.com success" }],
        starter(["n = int(input())", "for _ in range(n):", "    line = input()", "    # TODO: 이메일 사용자명을 마스킹하세요."]),
      ),
    ],
  },
];

export const mockExam = mockExams[0];

export const initialExamHistory: ExamHistory[] = [
  {
    id: "history-3",
    title: "자료구조 보충 테스트",
    roomCode: "DS-2401",
    submittedAt: "2026-05-21T16:20:00+09:00",
    score: 92,
    passedProblems: 5,
    totalProblems: 5,
    status: "채점 완료",
  },
  {
    id: "history-2",
    title: "알고리즘 중간 실습",
    roomCode: "ALGO-18",
    submittedAt: "2026-05-09T11:42:00+09:00",
    score: 78,
    passedProblems: 3,
    totalProblems: 4,
    status: "채점 완료",
  },
  {
    id: "history-1",
    title: "Python 기초 진단",
    roomCode: "PY-101",
    submittedAt: "2026-04-29T14:10:00+09:00",
    score: 100,
    passedProblems: 3,
    totalProblems: 3,
    status: "채점 완료",
  },
];
